# Generated by Django 3.2.12 on 2022-02-17 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Наименование')),
                ('short_name', models.CharField(max_length=32, unique=True, verbose_name='Короткое наименование')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=16, verbose_name='Версия')),
                ('start_date', models.DateField(verbose_name='Дата начала действия')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsi.catalog', verbose_name='Справочник')),
            ],
            options={
                'verbose_name': 'Версия справочника',
                'verbose_name_plural': 'Версии справочников',
                'ordering': ['catalog', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CatalogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='Код')),
                ('value', models.CharField(max_length=128, verbose_name='Значение')),
                ('catalog_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nsi.catalogversion', verbose_name='Версия справочника')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочников',
                'ordering': ['catalog_version', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='catalogversion',
            constraint=models.UniqueConstraint(fields=('catalog', 'version'), name='unique_catalog_version'),
        ),
        migrations.AddConstraint(
            model_name='catalogversion',
            constraint=models.UniqueConstraint(fields=('catalog', 'start_date'), name='unique_catalog_start_date'),
        ),
    ]
