# Generated by Django 3.2.12 on 2022-02-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='catalogcontent',
            constraint=models.CheckConstraint(check=models.Q(('code', ''), _negated=True), name='code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='catalogcontent',
            constraint=models.CheckConstraint(check=models.Q(('value', ''), _negated=True), name='value_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='catalogversion',
            constraint=models.CheckConstraint(check=models.Q(('version', ''), _negated=True), name='version_not_empty'),
        ),
    ]
