# Generated by Django 3.2.12 on 2022-02-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsi', '0002_auto_20220217_1203'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='catalogcontent',
            index=models.Index(fields=['catalog_version', 'code'], name='catalog_version_code_idx'),
        ),
    ]
